### ISSUE TITLE
plugin management

### ISSUE THREAD

**Issue by yanovich** [yanovich/abstract-accounting#1]
We need to figure out the best practice for using 3rd party code in the project. I've seen suggestions to use 'script/plugin' command and keep 3rd party code outside version control with '.gitignore'.

**Comment by sergeygaychuk** [comment]
In my opinion, we should use the rails Bundler.
Bundler overview: http://www.railsdispatch.com/posts/bundler

**Comment by yanovich** [comment]
Agreed.
