### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by sergeygaychuk** [yanovich/abstract-accounting#14]
Аутентификация содержит:
  Таблица ролей(CanCan), таблицу групп, таблицу полномочий, таблица прямого доступа.

После проверки CanCan
index
Создатель видит свои объекты
Начальник группы видит объекты всех подчинненых (по иерархии)
Если прошел проверку полномочий:
 Объект и вид работ и документ совпадают или пустой каждый
Если выдан прямой допуск

Страница создания роли:
Добавить разрешение на forward(возможность раздачи прямого доступа к объекту)
По умолчанию все галочки должны стоять.

**Comment by AlexeyShepelev** [comment]
Создана таблица role.

branch: uiv2
commit: <a href="https://github.com/AlexeyShepelev/abstract-accounting/commit/62a9ceff612d96a32249f3afbf86beb53de976dc">62a9ceff612d96a32249f3afbf86beb53de976dc</a>

**Comment by sergeygaychuk** [comment]
Проверено
branch: auth
commit: <a href="https://github.com/sergeygaychuk/abstract-accounting/commit/8d5a4ef8607b65373dfbe482b17c47d538612059">8d5a4ef8607b65373dfbe482b17c47d538612059</a>
