### ISSUE TITLE
Тестирование модели

### ISSUE THREAD

**Issue by sergeygaychuk** [yanovich/abstract-accounting#15]
В качестве тестовой системы использовать: rspec + factory_girl
Для ускорение использовать spork & guard
Перевести тестирование модели с TestUnit на Rspec

**Comment by AlexeyShepelev** [comment]
Перевёл:
asset, bug133, chart, deal, entity, income, money, quote, rule, state.

branch: model
commit: <a href="https://github.com/AlexeyShepelev/abstract-accounting/commit/d83c02ad3ca0f1baec2f98bab60bc4635a178e57"> d83c02ad3ca0f1baec2f98bab60bc4635a178e57 </a>

**Comment by sergeygaychuk** [comment]
Проверено
branch: model
last commit: <a href="https://github.com/sergeygaychuk/abstract-accounting/commit/1652aec884c3bc3905d46cc05cca99bbe126d686"> 1652aec884c3bc3905d46cc05cca99bbe126d686</a>
