### ISSUE TITLE
Таблица: тип работ

### ISSUE THREAD

**Issue by sergeygaychuk** [yanovich/abstract-accounting#22]
ID, Тип работ

**Comment by sergeygaychuk** [comment]
название на английском таблицы: works

**Comment by AlexeyShepelev** [comment]
Создана таблица works.

branch: uiv2
commit: <a href="https://github.com/AlexeyShepelev/abstract-accounting/commit/e4905792ef4d6c6000e1cbf34d8fc39afb979407">e4905792ef4d6c6000e1cbf34d8fc39afb979407</a>

**Comment by sergeygaychuk** [comment]
Проверено
branch: auth
commit: <a href="https://github.com/sergeygaychuk/abstract-accounting/commit/095a1a89736905c4ff536049df77c6c0859306fb">095a1a89736905c4ff536049df77c6c0859306fb</a>
