### ISSUE TITLE
Таблица полномочий

### ISSUE THREAD

**Issue by sergeygaychuk** [yanovich/abstract-accounting#24]
Таблица полномочий:
 Лицо
 Объект (место)
 Вид работ
 Тип документа (Накладная, Счет, Выдача и т. д.)

**Comment by sergeygaychuk** [comment]
Table: credentials
fields:
  entity, :references
  place, :references
  work, :references
  document_type, :string

**Comment by AlexeyShepelev** [comment]
Создана таблица полномочий.

branch: uiv2
commit: <a href="https://github.com/AlexeyShepelev/abstract-accounting/commit/c78bdf3255ea8331f4383ef4c509971cc74c299f">c78bdf3255ea8331f4383ef4c509971cc74c299f</a>

**Comment by sergeygaychuk** [comment]
Проверено
branch: auth
commit: <a href="https://github.com/sergeygaychuk/abstract-accounting/commit/03b5fb794544a7bf3f20f6d1e626c589be113ca2">03b5fb794544a7bf3f20f6d1e626c589be113ca2</a>
