### ISSUE TITLE
Таблица прямого допуска

### ISSUE THREAD

**Issue by sergeygaychuk** [yanovich/abstract-accounting#25]
Таблица прямого допуска:
 Лицо
 Тип документа
 Id документа

**Comment by sergeygaychuk** [comment]
table: dicrect_access
  entity, :references
  object, :polymorphic references

**Comment by AlexeyShepelev** [comment]
Создана таблица direct_access.

branch: uiv2
commit: <a href="https://github.com/AlexeyShepelev/abstract-accounting/commit/a77452d06c0699bbaa94fd86760fda51b6334417">a77452d06c0699bbaa94fd86760fda51b6334417</a>

**Comment by sergeygaychuk** [comment]
Проверено
branch: auth
commit: <a href="https://github.com/sergeygaychuk/abstract-accounting/commit/ac63d6eebc95bc69458cd354edbd71abe7c4a9e3">ac63d6eebc95bc69458cd354edbd71abe7c4a9e3</a>
