### ISSUE TITLE
Версии объектов

### ISSUE THREAD

**Issue by sergeygaychuk** [yanovich/abstract-accounting#26]
Необходимо добавить версии объектов в модель
Gem: paper_trail или схожие.

**Comment by AlexeyShepelev** [comment]
Установлен gem: paper_trail
Добавлены версии для моделей

branch: model
commit: <a href="https://github.com/AlexeyShepelev/abstract-accounting/commit/a62bc85c5f6d01816e03f910a8c213ca55702316">a62bc85c5f6d01816e03f910a8c213ca55702316</a>

**Comment by sergeygaychuk** [comment]
Проверено

branch: model
commit: <a href="https://github.com/sergeygaychuk/abstract-accounting/commit/3b807fa302c397296d917f83631540a34fc8e233">3b807fa302c397296d917f83631540a34fc8e233</a>
