### ISSUE TITLE
Аутентификация

### ISSUE THREAD

**Issue by sergeygaychuk** [yanovich/abstract-accounting#27]
Использовать Sorcery для авторизации.

**Comment by AlexeyShepelev** [comment]
Установлен gem: sorcery.
Данные для аутентификации учётной записи администратора берутся из файла конфигурации.
Реализованы возможности remember me и reset password.

branch: uiv2
commit: <a href="https://github.com/AlexeyShepelev/abstract-accounting/commit/343f711b4d04f6640c775b4ebd96a5aea7b901c7">343f711b4d04f6640c775b4ebd96a5aea7b901c7</a>

**Comment by sergeygaychuk** [comment]
Проверено
branch: auth
commit: <a href="https://github.com/sergeygaychuk/abstract-accounting/commit/980b7a2e81afe9528b9cee8fe9673f81851f460a">980b7a2e81afe9528b9cee8fe9673f81851f460a</a>
