### ISSUE TITLE
Таблица объектов (Place)

### ISSUE THREAD

**Issue by sergeygaychuk** [yanovich/abstract-accounting#28]
Поля: id, tag

**Comment by AlexeyShepelev** [comment]
Создана таблица объектов.

branch: uiv2
commit: <a href="https://github.com/AlexeyShepelev/abstract-accounting/commit/8b7cfc23ef8aa4581c54dacb0139e076e55bc370">8b7cfc23ef8aa4581c54dacb0139e076e55bc370</a>

**Comment by sergeygaychuk** [comment]
Проверено - залито в бранч auth
commit: <a href="https://github.com/sergeygaychuk/abstract-accounting/commit/35586e5710ce19982aff576bac0fcfd39b0db00f">35586e5710ce19982aff576bac0fcfd39b0db00f</a>
