### ISSUE TITLE
Переход на rails 3.1.0

### ISSUE THREAD

**Issue by sergeygaychuk** [yanovich/abstract-accounting#31]
надо перевести структуру папок и добавить необходимые gem-ы

**Comment by yanovich** [comment]
On 21/12/11 18:22, Sergey Gaychuk wrote:

> надо перевести структуру папок и добавить необходимые gem-ы

Да, давай.

И ещё пришли мне, пожалуйста, ссылку, как сделать, чтобы гемы ставились 
в vendor/

**Comment by AlexeyShepelev** [comment]
Перевёл

branch: auth
commit: <a href="https://github.com/AlexeyShepelev/abstract-accounting/commit/0386ff59991be759f80c4ba5c59925bb25c596cd">0386ff59991be759f80c4ba5c59925bb25c596cd</a>

**Comment by sergeygaychuk** [comment]
Проверено
branch: auth
commit: <a href="https://github.com/sergeygaychuk/abstract-accounting/commit/0386ff59991be759f80c4ba5c59925bb25c596cd">0386ff59991be759f80c4ba5c59925bb25c596cd</a>
