### ISSUE TITLE
speed up unit tests by DRYing

### ISSUE THREAD

**Issue by yanovich** [yanovich/abstract-accounting#7]
Remove repeating code from unit tests.

**Comment by AlexeyShepelev** [comment]
Выполнено. Время выполнения тестов уменьшено в 4 раза (с 16,4с до 4.2с).
В лог тестов записываются только ошибки.

branch: model
commit: <a href="https://github.com/AlexeyShepelev/abstract-accounting/commit/0bbcd2fb39abbe2621a7f11d75f62b77b59776c8">0bbcd2fb39abbe2621a7f11d75f62b77b59776c8</a>

**Comment by yanovich** [comment]
On 25/11/11 14:56, Alexey Shepelev wrote:

> Выполнено. Время выполнения тестов уменьшено в 4 раза (с 16,4с до 4.2с).
> В лог тестов записываются только ошибки.

Здорово

**Comment by sergeygaychuk** [comment]
Проверено
branch: model
commit: <a href="https://github.com/sergeygaychuk/abstract-accounting/commit/92a353ec43feefec931f595cd52ece014bf485d8">92a353ec43feefec931f595cd52ece014bf485d8</a>
